version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src/match-three
      - /usr/src/match-three/node_modules
    ports:
      - "${PORT}:${PORT}"
